<!DOCTYPE html>
<html>
    <head>

	<?php
	    Seo::displayHeader();

	    /* @var $Pagina MenuVO */
	    $Pagina = APP::getGlobal('Pagina');

	    /* @var $User UserVO */
	    $User = Module::getUserLoged();

	    $userImg160x160 = $User->imgCapa()->Redimensiona(160, 160);
	?>


        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <!--
    BODY TAG OPTIONS:
    =================
    Apply one or more of the following classes to get the
    desired effect
    |---------------------------------------------------------|
    | SKINS         | skin-blue                               |
    |               | skin-black                              |
    |               | skin-purple                             |
    |               | skin-yellow                             |
    |               | skin-red                                |
    |               | skin-green                              |
    |---------------------------------------------------------|
    |LAYOUT OPTIONS | fixed                                   |
    |               | layout-boxed                            |
    |               | layout-top-nav                          |
    |               | sidebar-collapse                        |
    |               | sidebar-mini                            |
    |---------------------------------------------------------|
    -->
    <body class="skin-blue sidebar-mini">
        <div class="wrapper">

            <!-- Main Header -->
            <header class="main-header">

                <!-- Logo -->
                <a href="<?= url() ?>" class="logo" title="Sercons" >
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><b>S</b>C</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg">Sercons</span>
                </a>

                <!-- Header Navbar -->
                <nav class="navbar navbar-static-top" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">

                            <!-- User Account Menu -->
                            <li class="dropdown user user-menu">
                                <!-- Menu Toggle Button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <!-- The user image in the navbar-->
                                    <img src="<?= $userImg160x160 ?>" class="user-image img-user" alt="Imagem do Usuário"/>
                                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                    <span class="hidden-xs"><?= Module::getUserLoged()->getNome() ?></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- The user image in the menu -->
                                    <li class="user-header">
                                        <img src="<?= $userImg160x160 ?>" class="img-circle img-user" alt="Imagem do Usuário" />
                                        <p>
					    <?= Module::getUserLoged()->getNome() ?>
                                            <small><?= Module::getUserLoged()->getTypeTitle() ?></small>
                                        </p>
                                    </li>

                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="<?= url('meus_dados') ?>" class="btn btn-default btn-flat">Meus dados</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="<?= url('logout') ?>" class="btn btn-default btn-flat">Sair</a>
                                        </div>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">

                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">

                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src="<?= $userImg160x160 ?>" class="img-circle img-user" alt="User Image" />
                        </div>
                        <div class="pull-left info">
                            <p><?= Module::getUserLoged()->getNome() ?></p>
                            <!-- Status -->
                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>

                    <!-- search form (Optional) -->
                    <form onSubmit="return false;" class="sidebar-form hide form-search">
                        <div class="input-group">
                            <input type="text" name="query" class="form-control" placeholder="Buscar..." />
                            <span class="input-group-btn">
                                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                    <!-- /.search form -->

		    <?php
			echo display_menu($Menu);

			function display_menu($Menu, $Nivel = 1) {
			    if ($Menu) {
				$html = '<ul class="' . ($Nivel == 1 ? 'sidebar-menu' : 'treeview-menu') . '" >';
				if ($Nivel == 1) {
				    $html .= '<li class="header" >Menu</li>';
				}
				foreach ($Menu as $m) {
				    $submenu = $m['submenu'];
				    $menu = $m['menu'];
				    $html .= '<li class="' . ($submenu ? 'treeview' : null) . '" >'
					    . display_menu_a($menu, $submenu)
					    . display_menu($submenu, $Nivel + 1)
					    . '</li>';
				}
				return $html . '</ul>';
			    } else {
				return null;
			    }
			}

			function display_menu_a(MenuVO $Menu, $Submenu = false) {
			    $html = '<a href="' . ($Menu->getController() ? url('page', [$Menu->getId()]) : '#' ) . '" '
				    . ($Menu->getOnClick() ? 'onClick="' . $Menu->getOnClick() . '" ' : null)
				    . '>'
				    . '<i class="' . ($Menu->getIcone() ? $Menu->getIcone() : 'fa fa-circle-o') . '" ></i> '
				    . '<span>'
				    . $Menu->getTitle()
				    . '</span> '
				    . ($Submenu ? '<i class="fa fa-angle-left pull-right"></i>' : null)
				    . '</a>';
			    return $html;
			}
		    ?>
                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <section class="content-header">
		    <?php
			if (!empty($Title)) {
			    echo '<h1>'
			    . $Title
			    . '<small>'
			    . @$Subtitle
			    . '</small>'
			    . '</h1>';
			} else if ($Pagina) {
			    echo '<h1>'
			    . $Pagina->getTitle()
			    . '<small>'
			    . $Pagina->getLegenda()
			    . '</small>'
			    . '</h1>'
			    . '<ol class="breadcrumb">'
			    . '<li><a href="' . url('') . '" ><i class="fa fa-dashboard" ></i> Principal</a></li>'
			    . call_user_func(function(MenuVO $v) {
				$menus = [];
				while ($v) {
				    $menus[] = $v;
				    $v = APP::getInstanceModel('Menu')->getByLabel('id', $v->getRoot());
				}
				$menus = array_reverse($menus);
				$html = '';
				foreach ($menus as $i => $v) {
				    $html .= '<li class="' . (!$i ? 'active' : null) . '" >'
					    . ($v->getIcone() ? '<i class="' . $v->getIcone() . '" ></i> ' : null)
					    . '<a href="' . ($v->getController() ? url('page', [$v->getId()]) : '#') . '" >'
					    . $v->getTitle()
					    . '</a>'
					    . '</li>';
				}
				return $html;
			    }, $Pagina)
			    . '</ol>';
			} else {
			    echo '<h1>'
			    . 'Página inválida.'
			    . '<small>'
			    . 'A página que tentou acessar é inválida.'
			    . '</small>'
			    . '</h1>';
			}
		    ?>
                </section>

                <section class="content"><?= $Body ?></section>

            </div><!-- /.content-wrapper -->

            <!-- Main Footer -->
            <footer class="main-footer">
                <!-- Default to the left -->
                <strong>&copy; <?= date('Y') ?> <a href="//www.lifeweb.com.br" target="_blank" >lifeweb.com.br</a>.</strong>
            </footer>

        </div><!-- ./wrapper -->

	<?php Seo::displayFooter() ?>
        <script>
            $('[data-search].adminpage').each(function () {
                $('.form-search').removeClass("hide");
                $(this).trigger('search', [{'search': $('.form-search [name=query]').val()}]);
            });
        </script>

    </body>
</html>