<div class="modal fade <?= $class ?>" id="<?= $id ?>" style="z-index: 99999999; padding: 0; width: 100%;" tabindex="-1" role="document" >
    <div class="modal-dialog modal-<?= $size ?>">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?= $title ?></h4>
            </div>
            <?php
                if (!empty($body)) {
                    echo '<div class="modal-body">' . $body . '</div>';
                }
                if (!empty($footer)) {
                    echo '<div class="modal-footer">' . $footer . '</div>';
                }
            ?>
        </div>
    </div>
</div>