<p class="text-center" ><?= $mensagem ?></p>
<div class="divider-30" ></div>

<?=
    form_open([
	'data-adminpage' => [
	    'saveValues' => ['assunto' => $assunto],
	    'controller' => 'contato',
	    'actionInsert' => 'contato_send',
	    'alertSuccess' => true,
	    'autoReset' => true,
	    'autoSearch' => false,
	]
    ]);
?>

<input type="text" name="nome1" class="hide" />
<input type="hidden" name="nome2" />

<div class="form-group" >
    <label>Nome</label>
    <input type="text" name="nome" required="" class="form-control input-lg" />
</div>
<div class="form-group" >
    <label>Telefone</label>
    <input type="text" name="telefone" required="" class="mask-telefone form-control input-lg" />
</div>
<div class="form-group" >
    <label>E-mail</label>
    <input type="text" name="email" required="" class="form-control input-lg" />
</div>
<div class="form-group" >
    <label>Estado</label>
    <input type="text" name="uf" required="" class="form-control input-lg" />
</div>
<div class="form-group" >
    <label>Cidade</label>
    <input type="text" name="cidade" required="" class="form-control input-lg" />
</div>
<div class="form-group" >
    <label>Mensagem</label>
    <textarea name="mensagem" required="" class="form-control input-lg" ></textarea>
</div>

<div class="text-right" >
    <button class="btn btn-danger btn-lg" >
	<i class="fa fa-send" ></i>
	Enviar
    </button>
</div>

<?= form_close(); ?>